### ISSUE TITLE
🍊 Add in `toBeGreaterThanOrEqualTo` function to Testing Library

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/eaf-linter#3]

**Comment by SumitKanth** [comment]
Hello, I want to contribute to your project, can you explain me what to do

**Comment by William-McGonagle** [comment]
@SumitKanth Sure- I need to add a setup and contributing section, but I'll let you know what to do.

1. In the testing area of the project, `src/tester/library.js`, there are a bunch of functions. 
2. Just copy the greater than function and rename it to greater than or equal to
3. Change the greater than symbol to a greater than or equal to symbol.

Then just send in the pull request and you'll be all set.

**Comment by SumitKanth** [comment]
> @SumitKanth Sure- I need to add a setup and contributing section, but I'll let you know what to do.
> 
> 1. In the testing area of the project, `src/tester/library.js`, there are a bunch of functions.
> 2. Just copy the greater than function and rename it to greater than or equal to
> 3. Change the greater than symbol to a greater than or equal to symbol.
> 
> Then just send in the pull request and you'll be all set.

@William-McGonagle - I will do this

**Comment by SumitKanth** [comment]
@William-McGonagle  I have done the changes, now what is the next step

**Comment by William-McGonagle** [comment]
You submitted a pull request and you're now a contributor to the project- thank you! You can keep solving issues or start working on one of the Fairfield Programming Association's other projects if you would like. :)

**Comment by SumitKanth** [comment]
@William-McGonagle  Can you tell me how to make pull request

**Comment by William-McGonagle** [comment]
Hey @SumitKanth- check out [this article](https://opensource.com/article/19/7/create-pull-request-github) on how to create a pull request.

**Comment by SumitKanth** [comment]
@William-McGonagle  I have created pull request, Now what is the next step

**Comment by Criticalcarpet** [comment]
@William-McGonagle 👋🏼  Opened a PR regarding the same... Please do take a look.  
Thank you

**Comment by William-McGonagle** [comment]
@Criticalcarpet Thank you for the pull request- your code all looked good!

**Comment by Criticalcarpet** [comment]
> @Criticalcarpet Thank you for the pull request- your code all looked good!

Your welcome... I will work on the README's now..
